# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Kamera_Ayarlari.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import styles



class Ui_Form(object):
    def setupUi(self, Form):

        self.font = QtGui.QFont()
        self.font.setFamily("Agency FB")
        self.font.setPointSize(12)
        self.font.setBold(True)
        self.font.setItalic(True)
        self.font.setWeight(75)
        
        Form.setObjectName("Form")
        Form.resize(561, 763)
        Form.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.sayfadakiGoruntuSayisi = QtWidgets.QSpinBox(Form)
        self.sayfadakiGoruntuSayisi.setGeometry(QtCore.QRect(270, 50, 91, 31))
   
        self.sayfadakiGoruntuSayisi.setFont(self.font)
        self.sayfadakiGoruntuSayisi.setStyleSheet("border: 3px solid gray; border-radius: 5px; \n""") 
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 50, 181, 31))
         
        self.label.setFont(self.font)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 170, 541, 551))
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.eslestirme = QtWidgets.QWidget()
        self.eslestirme.setObjectName("eslestirme")
        self.kamera_eslemeleri = QtWidgets.QScrollArea(self.eslestirme)
        self.kamera_eslemeleri.setGeometry(QtCore.QRect(10, 30, 511, 401))
        self.kamera_eslemeleri.setWidgetResizable(True)
        self.kamera_eslemeleri.setObjectName("kamera_eslemeleri")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 509, 399))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_7 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        
        self.label_3.setFont(self.font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_2.setStyleSheet(styles.styles["line_style"]) 
        self.horizontalLayout_6.addWidget(self.lineEdit_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_12.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_6.addWidget(self.pushButton_12)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_8.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_8)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setMaximumSize(QtCore.QSize(100, 16777215))
        
        self.label_8.setFont(self.font)
        self.label_8.setObjectName("label_8")

        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_3.setStyleSheet(styles.styles["line_style"]) 

        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_9.setMaximumSize(QtCore.QSize(50, 16777215))
        

        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_10.setMaximumSize(QtCore.QSize(50, 16777215))

        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_13.setMaximumSize(QtCore.QSize(50, 16777215))
        
        
        self.horizontalLayout_7.addWidget(self.label_8)
        self.horizontalLayout_7.addWidget(self.lineEdit_3)
        self.horizontalLayout_7.addWidget(self.pushButton_9)
        self.horizontalLayout_7.addWidget(self.pushButton_10)
        self.horizontalLayout_7.addWidget(self.pushButton_13)
        self.verticalLayout_4.addWidget(self.groupBox_8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.kamera_eslemeleri.setWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.addTab(self.eslestirme, "Kamera Eşleştirmeleri")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")

        self.comboBox_2 = QtWidgets.QComboBox(self.tab) 
        self.comboBox_2.setFont(self.font)
        self.comboBox_2.setStyleSheet(styles.styles["line_style"])  
        self.comboBox_2.addItem("Kamera1 - Noname")
        self.comboBox_2.addItem("Kamera1 - Noname") 
   
        
        self.verticalLayout.addWidget(self.comboBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(20, 60, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.checkBox.setFont(font)
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 30, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_2.setObjectName("checkBox_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(170, 110, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("border: 3px solid gray; border-radius: 5px; \n"
"")
        self.comboBox.setObjectName("comboBox")
        self.uyarilacak_cisimler = QtWidgets.QScrollArea(self.groupBox)
        self.uyarilacak_cisimler.setGeometry(QtCore.QRect(0, 170, 511, 211))
        self.uyarilacak_cisimler.setWidgetResizable(True)
        self.uyarilacak_cisimler.setObjectName("uyarilacak_cisimler")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 509, 209))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setMinimumSize(QtCore.QSize(220, 0))
        self.label_2.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setMinimumSize(QtCore.QSize(220, 0))
        self.label_5.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_4.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_4.addWidget(self.pushButton_8)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setMinimumSize(QtCore.QSize(220, 0))
        self.label_4.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.uyarilacak_cisimler.setWidget(self.scrollAreaWidgetContents)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 110, 141, 31))
        
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setGeometry(QtCore.QRect(420, 100, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet(styles.styles["button_style"])
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab, "")
        self.Degisim_suresi = QtWidgets.QDoubleSpinBox(Form)
        self.Degisim_suresi.setGeometry(QtCore.QRect(270, 110, 91, 31))
        self.Degisim_suresi.setStyleSheet("border: 3px solid gray; border-radius: 5px; \n")
        self.Degisim_suresi.setObjectName("Degisim_suresi")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(20, 100, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Sayfadaki görüntü Sayısı"))
        self.label_3.setText(_translate("Form", "KAMERA-0"))
        self.lineEdit_2.setText(_translate("Form", "NONAME"))
        self.pushButton_4.setText(_translate("Form", "Y"))
        self.pushButton_12.setText(_translate("Form", "A"))
        self.pushButton_3.setText(_translate("Form", "X"))
        self.label_8.setText(_translate("Form", "KAMERA-1"))
        self.lineEdit_3.setText(_translate("Form", "NONAME"))
        self.pushButton_9.setText(_translate("Form", "Y"))
        self.pushButton_10.setText(_translate("Form", "A"))
        self.pushButton_13.setText(_translate("Form", "X")) 
 
        self.groupBox.setTitle(_translate("Form", "Algılama"))
        self.checkBox.setText(_translate("Form", "Hareket algılama"))
        self.checkBox_2.setText(_translate("Form", "Nesne Takibi"))
        self.label_2.setText(_translate("Form", "İNSAN"))
        self.pushButton.setText(_translate("Form", "Alarm"))
        self.pushButton_2.setText(_translate("Form", "x"))
        self.label_5.setText(_translate("Form", "ARABA"))
        self.pushButton_7.setText(_translate("Form", "Alarm"))
        self.pushButton_8.setText(_translate("Form", "x"))
        self.label_4.setText(_translate("Form", "HAYVAN"))
        self.pushButton_5.setText(_translate("Form", "Alarm"))
        self.pushButton_6.setText(_translate("Form", "x"))
        self.label_6.setText(_translate("Form", "Uyarılacak cisimler"))
        self.pushButton_11.setText(_translate("Form", "Ekle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Yapay Zeka Ayarları"))
        self.label_7.setText(_translate("Form", "Otomatik Degisim Süresi (DK.SN)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
